# Generated by Django 5.0.6 on 2024-05-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medico", models.CharField(max_length=100)),
                ("especialidade", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Agendada"), ("C", "Cancelada")], max_length=100
                    ),
                ),
            ],
        ),
    ]
